services:
  db:
    image: mysql:5.7
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--init-connect='SET NAMES UTF8;'",
        "--innodb-flush-log-at-trx-commit=0",
      ]
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    healthcheck:
      test: "mysql -u${DB_USER} -p${DB_PASSWORD} -e 'select 1;'"
      interval: 1s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      LANG: C.UTF-8
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    

